{% set name = "xarrayutils" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xarrayutils-{{ version }}.tar.gz
  sha256: e157d6cf6a7e166e5a50a15d64cb2022af46bc30211a11e3f5a63f6985b7ceb9
  patches:
    - drop_versioneer.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - xarray >=0.14.1
    - numpy
    - matplotlib-base
    - scipy
    - astropy
    - dask

test:
  imports:
    - xarrayutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jbusecke/xarrayutils
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of various tools for data analysis built on top of xarray and xgcm

  description: This package contains a variety of utility functions I have used in the past few years for data analysis.
  dev_url: https://github.com/jbusecke/xarrayutils

extra:
  recipe-maintainers:
    - jbusecke
