{% set name = "xarrayutils" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1e5e2010a03fa22ae0d52d0d77636dcff90e83b49cbc3656636e430a8f6d6174

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - xarray
    - numpy
    - matplotlib
    - scipy
    - astropy
    - dask

test:
  imports:
    - xarrayutils

about:
  home: https://github.com/jbusecke/xarrayutils
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of various tools for data analysis built on top of xarray and xgcm

  description: This package contains a variety of utility functions I have used in the past few years for data analysis.
  dev_url: https://github.com/jbusecke/xarrayutils

extra:
  recipe-maintainers:
    - jbusecke
